"""Unit tests for Token-Saver Lockfile & Giant Asset Shield."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from token_saver.config import TokenSaverConfig
from token_saver.filters.lockfile import (
    DEFAULT_LOCKFILE_PATTERNS,
    find_package_in_lockfile,
    process_lockfile,
)
from token_saver.telemetry.stats import tracker
from token_saver.tools.smart_reader import read_file_smart


@pytest.fixture
def sample_npm_lock() -> str:
    """Create a realistic NPM package-lock.json v3."""
    packages = {
        "": {
            "name": "my-project",
            "version": "1.0.0",
            "dependencies": {
                "axios": "^1.6.8",
                "express": "^4.19.2",
                "react": "^18.2.0",
            },
        },
        "node_modules/axios": {
            "version": "1.6.8",
            "resolved": "https://registry.npmjs.org/axios/-/axios-1.6.8.tgz",
            "integrity": "sha512-WkG8P...",
            "dependencies": {
                "follow-redirects": "^1.15.6",
                "form-data": "^4.0.0",
            },
        },
        "node_modules/express": {
            "version": "4.19.2",
            "resolved": "https://registry.npmjs.org/express/-/express-4.19.2.tgz",
            "integrity": "sha512-ABC...",
        },
        "node_modules/react": {
            "version": "18.2.0",
            "resolved": "https://registry.npmjs.org/react/-/react-18.2.0.tgz",
        },
    }
    # Add 100 filler packages to simulate realistic size
    for i in range(100):
        packages[f"node_modules/sub-dependency-{i}"] = {
            "version": f"1.{i}.0",
            "resolved": f"https://registry.npmjs.org/sub-dep-{i}.tgz",
        }

    return json.dumps({
        "name": "my-project",
        "version": "1.0.0",
        "lockfileVersion": 3,
        "packages": packages,
    }, indent=2)


@pytest.fixture
def sample_cargo_lock() -> str:
    """Create a realistic Cargo.lock."""
    return """# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 3

[[package]]
name = "my_rust_app"
version = "0.1.0"
dependencies = [
 "serde",
 "tokio",
]

[[package]]
name = "serde"
version = "1.0.197"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "3fb1c873e1b9b056a4dc4c0c198b24c3ffa059243875552b2fc05328b07218b3"

[[package]]
name = "tokio"
version = "1.36.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "6145e0fcb043236e9cdd41c2c923573368570cbf2e5b0011e8a9c704f0f4e4f5"
dependencies = [
 "bytes",
 "pin-project-lite",
]
"""


@pytest.fixture
def sample_poetry_lock() -> str:
    """Create a realistic poetry.lock."""
    return """[[package]]
name = "requests"
version = "2.31.0"
description = "Python HTTP for Humans."
optional = false
python-versions = ">=3.7"
files = [
    {file = "requests-2.31.0-py3-none-any.whl", hash = "sha256:58ae44"},
]

[package.dependencies]
certifi = ">=2017.4.17"
charset-normalizer = ">=2,<4"
idna = ">=2.5,<4"
urllib3 = ">=1.21.1,<3"

[[package]]
name = "urllib3"
version = "2.2.1"
description = "HTTP library with thread-safe connection pooling."
optional = false
python-versions = ">=3.8"
"""


def test_npm_lockfile_shield_no_query(tmp_path: Path, sample_npm_lock: str):
    """Test reading package-lock.json without query returns compact summary."""
    lock_file = tmp_path / "package-lock.json"
    lock_file.write_text(sample_npm_lock, encoding="utf-8")

    result = read_file_smart(str(lock_file))
    assert "[TOKEN-SAVER SHIELD: package-lock.json]" in result
    assert "Lockfile Version: v3" in result
    assert "axios@" in result or "axios" in result
    assert "force_full=True" in result
    # Content must NOT dump full 100 packages
    assert "sub-dependency-99" not in result


def test_npm_lockfile_surgical_query(tmp_path: Path, sample_npm_lock: str):
    """Test querying a specific package returns only that package entry."""
    lock_file = tmp_path / "package-lock.json"
    lock_file.write_text(sample_npm_lock, encoding="utf-8")

    result = read_file_smart(str(lock_file), query="axios")
    assert "[TOKEN-SAVER SHIELD: package-lock.json] Package match for 'axios'" in result
    assert "1.6.8" in result
    assert "follow-redirects" in result
    # Other packages shouldn't be included in the surgical match
    assert "express" not in result
    assert "sub-dependency-50" not in result


def test_npm_lockfile_query_not_found(tmp_path: Path, sample_npm_lock: str):
    """Test querying a non-existent package returns a clean helpful message."""
    lock_file = tmp_path / "package-lock.json"
    lock_file.write_text(sample_npm_lock, encoding="utf-8")

    result = read_file_smart(str(lock_file), query="nonexistent-lib")
    assert "was NOT found in package-lock.json" in result
    assert "force_full=True" in result


def test_cargo_lockfile_shield(tmp_path: Path, sample_cargo_lock: str):
    """Test Cargo.lock shielding and surgical querying."""
    lock_file = tmp_path / "Cargo.lock"
    lock_file.write_text(sample_cargo_lock, encoding="utf-8")

    # 1. Summary
    res_sum = read_file_smart(str(lock_file))
    assert "[TOKEN-SAVER SHIELD: Cargo.lock]" in res_sum
    assert "Cargo locked packages:" in res_sum
    assert "tokio" in res_sum

    # 2. Query
    res_query = read_file_smart(str(lock_file), query="tokio")
    assert "[TOKEN-SAVER SHIELD: Cargo.lock] Package match for 'tokio'" in res_query
    assert 'name = "tokio"' in res_query
    assert 'version = "1.36.0"' in res_query
    assert "pin-project-lite" in res_query
    assert 'name = "serde"' not in res_query


def test_poetry_lockfile_shield(tmp_path: Path, sample_poetry_lock: str):
    """Test poetry.lock surgical querying."""
    lock_file = tmp_path / "poetry.lock"
    lock_file.write_text(sample_poetry_lock, encoding="utf-8")

    res_query = read_file_smart(str(lock_file), query="requests")
    assert "[TOKEN-SAVER SHIELD: poetry.lock] Package match for 'requests'" in res_query
    assert 'name = "requests"' in res_query
    assert 'version = "2.31.0"' in res_query
    assert "certifi" in res_query


def test_minified_asset_shield(tmp_path: Path):
    """Test that minified assets are shielded."""
    js_file = tmp_path / "bundle.min.js"
    js_content = "var a=1;function b(){return a+2;}" * 500
    js_file.write_text(js_content, encoding="utf-8")

    result = read_file_smart(str(js_file))
    assert "[TOKEN-SAVER SHIELD: bundle.min.js]" in result
    assert "Production Minified Asset" in result
    assert len(result) < 1000  # Masked!


def test_force_full_bypass(tmp_path: Path, sample_npm_lock: str):
    """Test force_full=True returns the raw full file without shielding."""
    lock_file = tmp_path / "package-lock.json"
    lock_file.write_text(sample_npm_lock, encoding="utf-8")

    result = read_file_smart(str(lock_file), force_full=True)
    assert "[TOKEN-SAVER SHIELD" not in result
    assert result == sample_npm_lock
    assert "sub-dependency-99" in result


def test_config_lockfile_shield_disabled(tmp_path: Path, sample_npm_lock: str):
    """Test that disabling lockfile_shield in config returns full content."""
    from token_saver.tools import smart_reader

    lock_file = tmp_path / "package-lock.json"
    lock_file.write_text(sample_npm_lock, encoding="utf-8")

    orig_cfg = smart_reader._config
    try:
        # Temporarily disable lockfile shield
        smart_reader._config = TokenSaverConfig(lockfile_shield=False)
        result = read_file_smart(str(lock_file))
        assert "[TOKEN-SAVER SHIELD" not in result
        assert result == sample_npm_lock
    finally:
        smart_reader._config = orig_cfg


def test_telemetry_records_lockfile_savings(tmp_path: Path, sample_npm_lock: str):
    """Verify that lockfile savings are properly tracked in telemetry."""
    lock_file = tmp_path / "package-lock.json"
    lock_file.write_text(sample_npm_lock, encoding="utf-8")

    prev_count = tracker.data.lockfile.count
    prev_saved = tracker.data.lockfile.saved

    read_file_smart(str(lock_file))

    assert tracker.data.lockfile.count == prev_count + 1
    assert tracker.data.lockfile.saved > prev_saved
